In [1]:
# Crear un environment
# python3 -m venv .venv
# Actualiza pip e instala lo básico para la utilizacion de jupyter nb en vscode
# uv pip install --upgrade pip
# uv pip install ipykernel

In [2]:
# Importar librerias pandas 
import pandas as pd

# The Series Object

La data unidimensional es representada por objetos de series.

In [3]:
# Creating a Series
# Con el siguiente codigo muestra el constructor que es usado para crear una nueva serie.
ser1 = pd.Series([10,20,30,40])
# Displaying the Series
ser1

0    10
1    20
2    30
3    40
dtype: int64

In [12]:
# Se pueden representar diferentes tipos de datos en las Series
ser2 =pd.Series([[10, 20],\
                 [30, 40.5, 'series'],\
                 [50, 55],\
                 {'Name': 'Tess', 'Org':'Packt'}])
ser2

0                            [10, 20]
1                  [30, 40.5, series]
2                            [50, 55]
3    {'Name': 'Tess', 'Org': 'Packt'}
dtype: object

# The Dataframe object

Un Dataframe es una representacion bi-dimensional de data en filas y columnas,

In [26]:
# Crear un Dataframe using the constructor
df = pd.DataFrame([30,50,20])
# En el codigo anterior, una lista de tres elementos fue convertido dentro del Constructor DataFrame()
# Mostrar
df

    0
0  30
1  50
2  20

In [27]:
# La salida es un DataFrame que puede ser visualizado usando el df.shape()
df.shape

(3, 1)

In [28]:
'''
Tu podrias ver 0 en la parte superior de la columna. Este es el nombre po defecto que este podria ser asignado a la columna cuando el Dataframe es creado.
Tu tambien podrias ver el numero 0, 1  y 2 a lo largo de las filas. Estas son llamadas indices.
'''
# Para mostrar las nombre de las columnas de los DataFrame, tu puedes usar el siguiente comando df.columns
df.columns

RangeIndex(start=0, stop=1, step=1)

In [29]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
# Tu puedes convertir estos dentro de una lista utilizando usando el siguiente comando list(). EL sioguiente atajo convierte los nombres de las columnas y los indicies de las filas dentro de listas y estos imprimen sus valoes.
print('These are the names od the columns', list(df.columns))
print('These are the row indices', list(df.index))
# Puedes ver esto en los nombres de las columnas y los indices de las filas representadas en una lista.

These are the names od the columns [0]
These are the row indices [0, 1, 2]

In [33]:
# Tambien puedes renombra las columnas y los indices de las filas para asignar estos para cualquier lista de valor.
# Este comando para renombrar una columna es df.columns.
# REnombra las columnas 
df.columns = ['V1']
df

   V1
0  30
1  50
2  20

In [36]:
# Renombrar los indices
df.index = ['R1', 'R2', 'R3']
df

    V1
R1  30
R2  50
R3  20

In [42]:
# Creacion de DAtaFrame con multiple columnas 
df1 = pd.DataFrame([[10, 15, 20],\
                    [100, 200, 300]])
print(f'Shape of new data frame', df1.shape)
df1

Shape of new data frame (2, 3)

     0    1    2
0   10   15   20
1  100  200  300