In [18]:
# Crear un environment
# python3 -m venv .venv
# Actualiza pip e instala lo básico para la utilizacion de jupyter nb en vscode
# uv pip install --upgrade pip
# uv pip install ipykernel

In [19]:
# Importar librerias pandas 
import pandas as pd

# The Series Object

La data unidimensional es representada por objetos de series.

In [20]:
# Creating a Series
# Con el siguiente codigo muestra el constructor que es usado para crear una nueva serie.
ser1 = pd.Series([10,20,30,40])
# Displaying the Series
ser1

0    10
1    20
2    30
3    40
dtype: int64

In [21]:
# Se pueden representar diferentes tipos de datos en las Series
ser2 =pd.Series([[10, 20],\
                 [30, 40.5, 'series'],\
                 [50, 55],\
                 {'Name': 'Tess', 'Org':'Packt'}])
ser2

0                            [10, 20]
1                  [30, 40.5, series]
2                            [50, 55]
3    {'Name': 'Tess', 'Org': 'Packt'}
dtype: object

# The Dataframe object

Un Dataframe es una representacion bi-dimensional de data en filas y columnas,

In [22]:
# Crear un Dataframe using the constructor
df = pd.DataFrame([30,50,20])
# En el codigo anterior, una lista de tres elementos fue convertido dentro del Constructor DataFrame()
# Mostrar
df

    0
0  30
1  50
2  20

In [23]:
# La salida es un DataFrame que puede ser visualizado usando el df.shape()
df.shape

(3, 1)

In [24]:
'''
Tu podrias ver 0 en la parte superior de la columna. Este es el nombre po defecto que este podria ser asignado a la columna cuando el Dataframe es creado.
Tu tambien podrias ver el numero 0, 1  y 2 a lo largo de las filas. Estas son llamadas indices.
'''
# Para mostrar las nombre de las columnas de los DataFrame, tu puedes usar el siguiente comando df.columns
df.columns

RangeIndex(start=0, stop=1, step=1)

In [25]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [26]:
# Tu puedes convertir estos dentro de una lista utilizando usando el siguiente comando list(). EL sioguiente atajo convierte los nombres de las columnas y los indicies de las filas dentro de listas y estos imprimen sus valoes.
print('These are the names od the columns', list(df.columns))
print('These are the row indices', list(df.index))
# Puedes ver esto en los nombres de las columnas y los indices de las filas representadas en una lista.

These are the names od the columns [0]
These are the row indices [0, 1, 2]

In [27]:
# Tambien puedes renombra las columnas y los indices de las filas para asignar estos para cualquier lista de valor.
# Este comando para renombrar una columna es df.columns.
# REnombra las columnas 
df.columns = ['V1']
df

   V1
0  30
1  50
2  20

In [28]:
# Renombrar los indices
df.index = ['R1', 'R2', 'R3']
df

    V1
R1  30
R2  50
R3  20

In [29]:
# Creacion de DataFrame con multiple columnas 
df1 = pd.DataFrame([[10, 15, 20],\
                    [100, 200, 300]])
print(f'Shape of new data frame', df1.shape)
df1

Shape of new data frame (2, 3)

     0    1    2
0   10   15   20
1  100  200  300

In [33]:
# Se pueden asignar los nombre de las columnas y los nombres de filas mientras se crea el DataFrame
df1 = pd.DataFrame([[10,15,20],[100,200,300]],\
                    columns= ['V1', 'V2', 'V3'],\
                    index= ['R1', 'R2'])
df1

     V1   V2   V3
R1   10   15   20
R2  100  200  300

# Working with local files

In [50]:
# EL prim,er paso es importar la data es para definir la ruta para el CSV, el segundo parametro es el delimitador, especifica como las diferentes columnas de data son separado dentro de el archivo.
studentData = pd.read_csv('../Activity1.01/student/student-por.csv', delimiter=';')

In [51]:
studentData.head(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [54]:
# Se pueden obtener snapshot de los dataset para visualizar solo las primeras y ultimas pocas filas.  Este es donde el head() y tail() las funciones resultan utiles.
studentData.tail(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [ ]:
# Toma las primeras cinco filas de la data este se almacena en otra variable llamada studentSmall.
studentSmall = studentData.head()
# Se define la ruta de salida para escribir el archivo
outpath = '../Activity1.01/student/studentSmall.csv'

In [ ]:
# Escribe la data en el directorio en el disco 
studentSmall.to_csv(outpath)

In [62]:
studentData.dtypes

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object